//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetBlog.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BlogModelResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BlogModelResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetBlog.Resources.BlogModelResources", typeof(BlogModelResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry(Html).
        /// </summary>
        public static string AddUpdateBlogEntry_Entry {
            get {
                return ResourceManager.GetString("AddUpdateBlogEntry_Entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword.
        /// </summary>
        public static string AddUpdateBlogEntry_Keyword {
            get {
                return ResourceManager.GetString("AddUpdateBlogEntry_Keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes to read.
        /// </summary>
        public static string AddUpdateBlogEntry_MinutesToRead {
            get {
                return ResourceManager.GetString("AddUpdateBlogEntry_MinutesToRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intro.
        /// </summary>
        public static string AddUpdateBlogEntry_TextIntro {
            get {
                return ResourceManager.GetString("AddUpdateBlogEntry_TextIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string AddUpdateBlogEntry_Title {
            get {
                return ResourceManager.GetString("AddUpdateBlogEntry_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uri.
        /// </summary>
        public static string AddUpdateBlogEntry_UriKey {
            get {
                return ResourceManager.GetString("AddUpdateBlogEntry_UriKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volver a listado.
        /// </summary>
        public static string BackToBlogList {
            get {
                return ResourceManager.GetString("BackToBlogList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new blog entry.
        /// </summary>
        public static string BlogEntryAddPageHeading {
            get {
                return ResourceManager.GetString("BlogEntryAddPageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are some errors saving the blog entry.
        /// </summary>
        public static string BlogEntryErrorsTitle {
            get {
                return ResourceManager.GetString("BlogEntryErrorsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Blog entry.
        /// </summary>
        public static string BlogEntryUpdatePageHeading {
            get {
                return ResourceManager.GetString("BlogEntryUpdatePageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new blog.
        /// </summary>
        public static string BlogIndex_AddBlogLabel {
            get {
                return ResourceManager.GetString("BlogIndex_AddBlogLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation is invalied due to the blog´s state.
        /// </summary>
        public static string BlogState_InvalidStateError {
            get {
                return ResourceManager.GetString("BlogState_InvalidStateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database error savin the info, please contact support.
        /// </summary>
        public static string BlogState_StorageError {
            get {
                return ResourceManager.GetString("BlogState_StorageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an existing blog entry with the same uri.
        /// </summary>
        public static string BlogState_UriKeyDuplicateError {
            get {
                return ResourceManager.GetString("BlogState_UriKeyDuplicateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue reading.
        /// </summary>
        public static string ContinueReading {
            get {
                return ResourceManager.GetString("ContinueReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit blog.
        /// </summary>
        public static string EditBlogLabel {
            get {
                return ResourceManager.GetString("EditBlogLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog archives.
        /// </summary>
        public static string HeaderTitle {
            get {
                return ResourceManager.GetString("HeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute(s) to read.
        /// </summary>
        public static string MinutesToRead {
            get {
                return ResourceManager.GetString("MinutesToRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records in current page.
        /// </summary>
        public static string PageWithNoItems {
            get {
                return ResourceManager.GetString("PageWithNoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog list.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
