//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetBlog.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GridResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GridResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetBlog.Resources.GridResources", typeof(GridResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrando.
        /// </summary>
        public static string Grid_DisplayingLabel {
            get {
                return ResourceManager.GetString("Grid_DisplayingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50 registros.
        /// </summary>
        public static string Grid_FiftyRows {
            get {
                return ResourceManager.GetString("Grid_FiftyRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primer Página.
        /// </summary>
        public static string Grid_FirstPageLabel {
            get {
                return ResourceManager.GetString("Grid_FirstPageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siguiente.
        /// </summary>
        public static string Grid_NextPageLabel {
            get {
                return ResourceManager.GetString("Grid_NextPageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Página.
        /// </summary>
        public static string Grid_PageLabel {
            get {
                return ResourceManager.GetString("Grid_PageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de.
        /// </summary>
        public static string Grid_PageNumberOfLabel {
            get {
                return ResourceManager.GetString("Grid_PageNumberOfLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anterior.
        /// </summary>
        public static string Grid_PreviousPageLabel {
            get {
                return ResourceManager.GetString("Grid_PreviousPageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to registros..
        /// </summary>
        public static string Grid_RowsLabel {
            get {
                return ResourceManager.GetString("Grid_RowsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        public static string Grid_SearchButtonLabel {
            get {
                return ResourceManager.GetString("Grid_SearchButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 registros.
        /// </summary>
        public static string Grid_TenRows {
            get {
                return ResourceManager.GetString("Grid_TenRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 registros.
        /// </summary>
        public static string Grid_ThirtyRows {
            get {
                return ResourceManager.GetString("Grid_ThirtyRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20 registros.
        /// </summary>
        public static string Grid_TwentyRows {
            get {
                return ResourceManager.GetString("Grid_TwentyRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se encuentra en la página.
        /// </summary>
        public static string Grid_YouAreOnPageLabel {
            get {
                return ResourceManager.GetString("Grid_YouAreOnPageLabel", resourceCulture);
            }
        }
    }
}
